"""Define common field types in an easy to modify manner."""
from easyprotocol.fields.signed_int import IntField as IntField  # noqa
from easyprotocol.fields.signed_int import Int8Field as Int8Field  # noqa
from easyprotocol.fields.signed_int import Int16Field as Int16Field  # noqa
from easyprotocol.fields.signed_int import Int32Field as Int32Field  # noqa
from easyprotocol.fields.signed_int import Int64Field as Int64Field  # noqa
from easyprotocol.fields.unsigned_int import UIntField as UIntField  # noqa
from easyprotocol.fields.unsigned_int import UInt8Field as UInt8Field  # noqa
from easyprotocol.fields.unsigned_int import UInt16Field as UInt16Field  # noqa
from easyprotocol.fields.unsigned_int import UInt32Field as UInt32Field  # noqa
from easyprotocol.fields.unsigned_int import UInt64Field as UInt64Field  # noqa
from easyprotocol.fields.enum import EnumField as EnumField  # noqa
from easyprotocol.fields.enum import UInt8EnumField as UInt8EnumField  # noqa
from easyprotocol.fields.enum import UInt16EnumField as UInt16EnumField  # noqa
from easyprotocol.fields.enum import UInt24EnumField as UInt24EnumField  # noqa
from easyprotocol.fields.enum import UInt32EnumField as UInt32EnumField  # noqa
from easyprotocol.fields.array import ArrayField as ArrayField  # noqa
from easyprotocol.fields.checksum import ChecksumField as ChecksumField  # noqa
from easyprotocol.fields.unsigned_int import BoolField as BoolField  # noqa
from easyprotocol.fields.float import FloatField as FloatField  # noqa
from easyprotocol.fields.float import Float32IEEField as Float32IEEField  # noqa
